      - name: OpenTofu Apply
        env:
          OPENTOFU_ENVIRONMENT_GATED: "true"
          NAMECHEAP_API_KEY: ${{ secrets.NAMECHEAP_API_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: make apply
